{% set name = "requests_cache" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("_", "-" ) }}-{{ version }}.tar.gz
  sha256: 6822f788c5ee248995c4bfbd725de2002ad710182ba26a666e85b64981866060

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=1.1.0

test:
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.backends.storage

about:
  home: https://github.com/reclosedev/requests-cache
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: Persistent cache for requests library

  description: |
    Requests-cache is a transparent persistent cache for requests (version >= 1.1.0) library.
  doc_url: https://requests-cache.readthedocs.io/
  dev_url: https://github.com/reclosedev/requests-cache

extra:
  recipe-maintainers:
    - andreyz4k
