travis:
  secure:
    BINSTAR_TOKEN: 2nXwRa+el2mtevZxd17qeLJDqX/AKKNe4Bq5HO+0By1oqKs5OzTSUNwwH5vZ5PuYfE+scPzV5OR3owzba8bZHv0RhI3lb8tbuqSUWoOTuF6Des1JqNVyO/9e13f7lOgb0y+pQHwkNdAT+xAnG5XqtAEQI4MlC84Quq8wgsKFg5bHpkmtSdpMhyRC1SMeOs4Vvyyyg6Y7Wwlqew38q6EN14G9oU+zVp6Ujq8gNufNyrYlK8U1Qkt5uvroBB7c2FrvjR0OP3YBo2LpUqUtdUT0XfrmEzNQq3plMXPY64OGmDc6xAVLENdcoCqi6kJGMl56IaJ8hkuCg/kFruaLNvA4ZcJJ2yjsCZpKTwgSKkssZ7XMrxMLn58ac9Jdp5Kups2IwkGAyKJ7LFTe8DtbiPoKjRdgSkW0opcnE7eYMuR5gBkQXl8fwtUnpM9WfS2d686o07CR98l6zhvjltnHNlQ+a5Bbl2zsqGx5Vs0kDfHHSIqLzCgloAE4t7UqZBfADrS2f6wnEVSTZyXup7qsKh2WiWgd2awEx4lYBlSgKBCbx618uxCZuyG08543WiumhzDdZE9PRm1/HjNsugNShy6468oJ4be9UPWlq5u+DobswyLmOmmHIbBOzVvj/cFbe0G76o/VSt1KDv8ZZQfKljxz8SiwZff1iNKrCEWyOdM6C4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
